name: refreshing_nicolas
services:
  client:
    cpu_shares: 90
    command:
      - nginx
      - -g
      - daemon off;
    container_name: civis-client
    depends_on:
      server:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 16562188288
        reservations:
          devices: []
    image: docker.io/jucraft0/civis-client:latest
    labels:
      icon: https://raw.githubusercontent.com/JuCraft0/Civis/d85b2339570839e473c98b9480051aabaf22b5a9/extension_icon.png
    ports:
      - target: 10000
        published: "10001"
        protocol: tcp
    restart: unless-stopped
    volumes: []
    devices: []
    cap_add: []
    environment: []
    networks:
      - civis-net
    privileged: false
  db:
    cpu_shares: 90
    command: []
    container_name: civis-db
    deploy:
      resources:
        limits:
          memory: 16562188288
        reservations:
          devices: []
    environment:
      - POSTGRES_DB=civis
      - POSTGRES_PASSWORD=civis
      - POSTGRES_USER=civis
    image: docker.io/library/postgres:15-alpine
    labels:
      icon: https://raw.githubusercontent.com/JuCraft0/Civis/d85b2339570839e473c98b9480051aabaf22b5a9/extension_icon.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/civis/postgres
        target: /var/lib/postgresql/data
    ports: []
    devices: []
    cap_add: []
    networks:
      - civis-net
    privileged: false
  face-ai:
    cpu_shares: 90
    command: []
    container_name: civis-face-ai
    deploy:
      resources:
        limits:
          memory: 4294967296
        reservations:
          devices: []
    environment:
      - IMMICH_API=CXBIR9TJHQNar7tWiPMHz0cLTdb0bnqZG4dDogAcG7g
      - IMMICH_URL=https://foto.jcpconnect.de/api
    image: docker.io/jucraft0/civis-face-ai:latest
    labels:
      icon: https://raw.githubusercontent.com/JuCraft0/Civis/d85b2339570839e473c98b9480051aabaf22b5a9/extension_icon.png
    restart: unless-stopped
    volumes:
      - type: volume
        target: /root/.deepface/weights
    ports: []
    devices: []
    cap_add: []
    networks:
      - civis-net
    privileged: false
  server:
    cpu_shares: 90
    command:
      - node
      - index.js
    container_name: civis-server
    depends_on:
      db:
        condition: service_started
        required: true
      face-ai:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 16562188288
        reservations:
          devices: []
    environment:
      - DATABASE_URL=postgres://civis:civis@db:5432/civis
      - FACE_AI_URL=http://face-ai:8000
      - IMMICH_API_KEY=CXBIR9TJHQNar7tWiPMHz0cLTdb0bnqZG4dDogAcG7g
      - IMMICH_URL=https://foto.jcpconnect.de
      - NODE_ENV=production
      - PORT=5005
    image: docker.io/jucraft0/civis-server:latest
    labels:
      icon: https://raw.githubusercontent.com/JuCraft0/Civis/d85b2339570839e473c98b9480051aabaf22b5a9/extension_icon.png
    restart: unless-stopped
    ports: []
    volumes: []
    devices: []
    cap_add: []
    networks:
      - civis-net
    privileged: false
networks:
  civis-net:
    name: refreshing_nicolas_civis-net
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  author: JuCraft0
  category: Utilities
  description:
    de_de: Personenverwaltung mit Gesichtserkennung.
    en_us: People management application with face recognition.
  hostname: civisos.jcpconnect.de/
  icon: https://raw.githubusercontent.com/JuCraft0/Civis/d85b2339570839e473c98b9480051aabaf22b5a9/extension_icon.png
  index: /
  is_uncontrolled: false
  main: client
  port_map: "10001"
  scheme: http
  store_app_id: refreshing_nicolas
  title:
    custom: ""
    de_de: Civis
    en_us: Civis
